name: Backend Validate

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # バックエンドのビルド
      - name: Build Backend
        run: |
          cd backend
          chmod +x ./build.sh
          ./build.sh chat
          
      - name: Build Vectorize Backend
        run: |
          cd backend
          chmod +x ./build.sh
          ./build.sh vectorize
