name: CI/CD Pipeline - Backend

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  # backend validate
  backend_validate:
    uses: ./.github/workflows/backend_validate.yaml
    if: github.event_name == 'pull_request'
    secrets: inherit
    with:
      environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

  # backend deploy
  backend_deploy:
    uses: ./.github/workflows/backend_deploy.yaml
    if: github.event_name == 'push'
    secrets: inherit
    with:
      environment: ${{ github.ref_name == 'main' && 'prd' || 'dev' }}
