name: Backend Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # バックエンドのビルド
      - name: Build Chat Backend
        run: |
          cd backend
          chmod +x ./build.sh
          ./build.sh chat
          echo "zip_path=$(pwd)/chat/lambda_function.zip" >> $GITHUB_OUTPUT
          
      - name: Build Vectorize Backend
        run: |
          cd backend
          chmod +x ./build.sh
          ./build.sh vectorize
          echo "zip_path=$(pwd)/vectorize/lambda_function.zip" >> $GITHUB_OUTPUT
      
      - name: Upload Chat Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chat-lambda-zip
          path: ${{ steps.build_chat.outputs.zip_path }}
      
      - name: Upload Vectorize Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vectorize-lambda-zip
          path: ${{ steps.build_vectorize.outputs.zip_path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download Chat Artifact
        uses: actions/download-artifact@v3
        with:
          name: chat-lambda-zip
          path: backend/chat
      
      - name: Download Vectorize Artifact
        uses: actions/download-artifact@v3
        with:
          name: vectorize-lambda-zip
          path: backend/vectorize
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # lambrollのインストール
      - name: Install lambroll
        uses: fujiwara/lambroll@v1
        with:
          version: v1.1.3

      # Lambda関数のデプロイ
      - name: Deploy Chat Lambda
        run: |
          cd backend/chat
          lambroll deploy --src="lambda_function.zip"
      
      - name: Deploy Vectorize Lambda
        run: |
          cd backend/vectorize
          lambroll deploy --src="lambda_function.zip"
