name: Infrastructure CI/CD Pipeline

on:
  push:
    paths:
      - 'infra/**'
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Terraformのセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Terraformの初期化とPlan
      - name: Plan Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AURORA_MASTER_PASSWORD: ${{ secrets.TF_VAR_AURORA_MASTER_PASSWORD }}
          TF_VAR_OPENAI_API_KEY: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
        run: |
          cd infra
          terraform init -backend-config=envs/dev/dev.tfbackend
          terraform plan

      # TerraformのApply
      - name: Plan Terraform (Production)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AURORA_MASTER_PASSWORD: ${{ secrets.TF_VAR_AURORA_MASTER_PASSWORD }}
          TF_VAR_OPENAI_API_KEY: ${{ secrets.TF_VAR_OPENAI_API_KEY }}
        run: |
          cd infra
          terraform apply -auto-approve
