name: Infrastructure CI/CD Pipeline

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Terraformのセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Download tfvars from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp s3://marcy-dev-terraform/variables/terraform.dev.tfvars ./terraform.dev.tfvars

      # Terraformの初期化とPlan
      - name: Plan Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd infra
          terraform init -backend-config=envs/dev/dev.tfbackend
          terraform plan -var-file=../terraform.dev.tfvars

      # TerraformのApply
      - name: Apply Terraform (Production)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd infra
          terraform apply -var-file=../terraform.dev.tfvars -auto-approve
