name: CI/CD Pipeline - Infra

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - '.github/workflows/**'

jobs:
  # infra validate
  infra_validate:
    uses: ./.github/workflows/infra_validate.yaml
    if: github.event_name == 'pull_request'
    secrets: inherit
    with:
      environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

  # infra deploy
  infra_deploy:
    needs: infra_validate
    uses: ./.github/workflows/infra_deploy.yaml
    if: github.event_name == 'push'
    secrets: inherit
    with:
      environment: ${{ github.ref_name == 'main' && 'prd' || 'dev' }}

  # backend redeploy after infra deploy
  backend_redeploy:
    needs: infra_deploy
    uses: ./.github/workflows/backend_deploy.yaml
    if: github.event_name == 'push'
    secrets: inherit
    with:
      environment: ${{ github.ref_name == 'main' && 'prd' || 'dev' }}