name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  # infra verify and deploy
  infra:
    uses: ./.github/workflows/infra.yaml
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'infra'))
    secrets: inherit
    with:
       environment: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'prd' || github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main' && 'prd' || 'dev' }}
  
  # backend verify and deploy
  # backend:
  #   needs: infra
  #   uses: ./.github/workflows/backend.yaml
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'backend'))
  #   secrets: inherit
  #   with:
  #      environment: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'prd' || github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main' && 'prd' || 'dev' }}
