name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  # infra validate
  infra_validate:
    uses: ./.github/workflows/infra_validate.yaml
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'infra')
    secrets: inherit
    with:
      environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

  # infra deploy
  infra_deploy:
    needs: infra_verify
    uses: ./.github/workflows/infra_deploy.yaml
    if: github.event_name == 'push' && contains(github.event.push.changed_files, 'infra')
    secrets: inherit
    with:
      environment: ${{ github.ref_name == 'main' && 'prd' || 'dev' }}

  # # backend verify
  # backend_verify:
  #   uses: ./.github/workflows/backend_verify.yaml
  #   if: github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'backend')
  #   secrets: inherit
  #   with:
  #     environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

  # # backend deploy
  # backend_deploy:
  #   needs: backend_verify
  #   uses: ./.github/workflows/backend_deploy.yaml
  #   if: github.event_name == 'push' && contains(github.event.push.changed_files, 'backend')
  #   secrets: inherit
  #   with:
  #     environment: ${{ github.ref_name == 'main' && 'prd' || 'dev' }}