name: CI/CD Pipeline - Pull Request

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - '.github/workflows/**'

env:
  environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

jobs:
  changed-files:
    runs-on: ubuntu-latest
    environment: ${{ env.environment }}
    outputs:
      infra_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'infra/') }}
    steps: 
      - id: changed-files
        uses: tj-actions/changed-files@v45
  
  infra-validate:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.infra_changed == 'true' }}
    environment: ${{ env.environment }}
    uses: ./.github/workflows/infra_validate.yaml
    secrets: inherit
    with:
      environment: ${{ env.environment }}
