name: CI/CD Pipeline - Pull Request

on:
  pull-request:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - '.github/workflows/**'

env:
  environment: ${{ github.ref_name == 'main' && 'prd' || 'dev' }}

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'infra') }}
      backend_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'backend') }}
    steps: 
      - id: changed-files
        uses: tj-actions/changed-files@v45
  
  Infra validate workflow:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.infra_changed }}
    steps:
      - name: Infra validate
        uses: ./.github/workflows/infra_validate.yaml
        secrets: inherit
        with:
          environment: ${{ env.environment }}
