name: CI/CD Pipeline - Push

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - 'backend/**'
      - '.github/workflows/**'

env:
  environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'infra') }}
      backend_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'backend') }}
    steps: 
      - id: changed-files
        uses: tj-actions/changed-files@v45
  
  Infra deploy workflow:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.infra_changed }}
    steps:
      - name: Infra deploy
        uses: ./.github/workflows/infra_deploy.yaml
        with:
          environment: ${{ env.environment }}
      - name: Backend deploy
        uses: ./.github/workflows/backend_deploy.yaml
        with:
          environment: ${{ env.environment }}
    secrets: inherit
  
  Backend deploy workflow:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ !needs.changed-files.outputs.infra_changed && needs.changed-files.outputs.backend_changed }}
    steps:
      - name: Backend deploy
        uses: ./.github/workflows/backend_deploy.yaml
        with:
          environment: ${{ env.environment }}
    secrets: inherit
