name: CI/CD Pipeline - Push

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - 'backend/**'
      - '.github/workflows/**'

env:
  environment: ${{ github.event.pull_request.base.ref == 'main' && 'prd' || 'dev' }}

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'infra') }}
      backend_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'backend') }}
    steps: 
      - id: changed-files
        uses: tj-actions/changed-files@v45
  
  infra-deploy:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.infra_changed }}
    uses: ./.github/workflows/infra_deploy.yaml
    secrets: inherit
    with:
      environment: ${{ env.environment }}

  backend-deploy-after-infra-deployment
    runs-on: ubuntu-latest
    needs: [changed-files, infra-deploy]
    if: ${{ needs.changed-files.outputs.infra_changed }}
    uses: ./.github/workflows/backend_deploy.yaml
    secrets: inherit
    with:
      environment: ${{ env.environment }}
  
  backend-deploy-without-infra-deployment:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ !needs.changed-files.outputs.infra_changed && needs.changed-files.outputs.backend_changed }}
    uses: ./.github/workflows/backend_deploy.yaml
    secrets: inherit
    with:
      environment: ${{ env.environment }}
