name: CI/CD Pipeline - Push

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
      - 'backend/**'
      - '.github/workflows/**'

environment: ${{ github.ref_name == 'main' && 'prd' || 'dev' }}
env:
  env: ${{ github.ref_name == 'main' && 'prd' || 'dev' }}

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'infra/') }}
      backend_changed: ${{ contains(steps.changed-files.outputs.modified_files, 'backend/') }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: changed-files
        uses: tj-actions/changed-files@v45
  
  infra-deploy:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.infra_changed == 'true'  }}
    uses: ./.github/workflows/infra_deploy.yaml
    secrets: inherit
    with:
      environment: ${{ env.env }}

  backend-deploy-after-infra-deployment:
    needs: [changed-files, infra-deploy]
    if: ${{ needs.changed-files.outputs.infra_changed == 'true' }}
    uses: ./.github/workflows/backend_deploy.yaml
    secrets: inherit
    with:
      environment: ${{ env.env }}
  
  backend-deploy-without-infra-deployment:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.infra_changed == 'false' && needs.changed-files.outputs.backend_changed == 'true' }}
    uses: ./.github/workflows/backend_deploy.yaml
    secrets: inherit
    with:
      environment: ${{ env.env }}
